### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Ca-moes** [Ca-moes/feup-plog-proj#20]
- [ ] Menus Bonitos 
   - Pôr uma interface melhor em vez de ser só texto
   - brincar com `clear`, acho que assim está bom o uso (clear no inicio de menu principal e antes de cada display do board)
- [ ] Passar `X, Y` para `X-Y` nos lugares possíveis, por exemplo, na linha 17 de `logic.pl` tem um comentário para o predicado `choose_piece`
- [ ] Linhas 117-121 de `logic.pl` simplificar aquilo
- [ ] Relatório - ter atenção ao que o stor disse na primeira entrega
> - Não submeteram imagens
> - Regras podiam estar um pouco mais claras (caminhos/lados) 
> - representação ok
> - Visualização poderia ficar melhor sem separação nas coordenadas, e com + nas interseções de linhas em vez de |
> - predicados de visualização podia ser flexível para diferentes tamanhos de tabuleiro
> - row e check... podiam ser mais declarativos
